name: toodo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.22.0
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.0
  signals: ^6.3.0
  signals_flutter: ^6.3.0
  go_router: ^14.6.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  shared_preferences: ^2.3.3
  flutter_timezone: ^5.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.22.0
  build_runner: ^2.4.13
  sqlite3: ^2.5.0

flutter:
  uses-material-design: true
